### ISSUE TITLE
Instances will override other instances

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-toggle#2]
The component stores each instance of itself against an internal property, using the toggle element as the key.

However because the `_toggles` property is a plain object the toggle element will be stringified when used as a key. Therefore if 2 or more toggles are of the same node type the previous will be overridden. This causes no problems when setting up toggles but it means that toggles cannot be destroyed.

I've created a simplified demo of the problem here: http://jsbin.com/waziporowe/1/edit?html,js,console

**Comment by AlbertoElias** [comment]
Fixed in #4
